# Generated by Django 5.0.1 on 2024-02-23 06:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_remove_workschedule_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
