# Generated by Django 5.0.1 on 2024-02-23 07:22

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_alter_doctor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
