# Generated by Django 5.0.1 on 2024-02-23 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_alter_doctor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
